name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  CI:
    # runs-on: ubuntu-latest
    uses: ./.github/workflows/ci.yml
    with:
        message: "Hello from CI"

  CD_DEV:
    needs: CI
    # runs-on: ubuntu-latest
    uses: ./.github/workflows/cd.yml
    with:
        message: "Hello from CD_DEV"
        env_prep_msg: "hello NPE env prep"
        environment: dev

  CD_NPE:
    needs: CD_DEV
    # runs-on: ubuntu-latest
    uses: ./.github/workflows/cd.yml
    with:
        message: "Hello from CD_NPE"
        env_prep_msg: "hello NPE env prep"
        environment: npe

  CD_PROD1:
    needs: CD_NPE
    uses: ./.github/workflows/cd.yml
    with:
        message: "Hello from CD_PROD1"
        env_prep_msg: "hello prod env prep"
        environment: prod1

  CD_PROD2:
    needs: CD_NPE
    uses: ./.github/workflows/cd.yml
    with:
        message: "Hello from CD_PROD2"
        env_prep_msg: "hello prod2 env prep"
        environment: prod2


    # - uses: ./.github/workflows/ci.yml
    #   with:
    #     message: "Hello from Next step"