name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/workflows/ci.yml
      with:
        message: "Hello from CI"

  CD_DEV:
    needs: CI
    steps:
    - uses: ./.github/workflows/ci.yml
      with:
        message: "Hello from CD_DEV"

  CD_NPE:
    needs: CD_DEV
    steps:
    - uses: ./.github/workflows/ci.yml
      with:
        message: "Hello from CD_NPE"

  CD_PROD1:
    needs: CD_NPE
    steps:
    - uses: ./.github/workflows/ci.yml
      with:
        message: "Hello from CD_PROD1"

  CD_PROD2:
    needs: CD_NPE
    steps:
    - uses: ./.github/workflows/ci.yml
      with:
        message: "Hello from CD_PROD2"


    # - uses: ./.github/workflows/ci.yml
    #   with:
    #     message: "Hello from Next step"